language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:

# migration test
  - python3 manage.py migrate --noinput

# PEP8
  - flake8

script:
  - coverage run manage.py test --settings=tutorial.settings.test --failfast

after_success:
  - codecov
